_common/urls.py
from django.urls import path

# import hostlock views and apis
from _common import views

app_name = "_common"


urlpatterns = [

    # action views
    # path('update_token/', views.UpdateApiToken.as_view(), name='update_token'),

    # custom views
    path('show_admin/', views.ShowAdminPage.as_view(), name='show_admin'),

    # list views
    path('list_recents/', views.ListRecents.as_view(), name='list_recents'),
    path('list_favorites/', views.ListFavorites.as_view(), name='list_favorites'),

]

hostlock/urls.py
from django.urls import path
from django.conf.urls import include
from rest_framework.routers import DefaultRouter

# import hostlock views and apis
import hostlock.views.views_gui as gui
import hostlock.views.views_api as api
import hostlock.views.views_ajax as ajax

app_name = "hostlock"

router = DefaultRouter()

# hostlock API Endpoints
router.register(r'host', api.HostViewSet, "host")
router.register(r'lock', api.LockViewSet, "lock")
router.register(r'grant_lock', api.GrantLockViewSet, "grant_lock")


urlpatterns = [

    # API views
    path('api/', include(router.urls)),
    path('api/v1/', include(router.urls)),
    path('api/v1/extend_lock/', api.ExtendLockViewSet.as_view()),
    path('api/v1/release_lock/', api.ReleaseLockViewSet.as_view()),
    path('api/v1/check_lock/', api.CheckLockViewSet.as_view()),


    # home page urls
    path('', gui.HostLockIndex.as_view(), name='index'),
    path('home', gui.HostLockIndex.as_view(), name='home'),
    path('default', gui.HostLockIndex.as_view(), name='default'),

    # custom views
    path('hostlock_dashboard/', gui.HostLockDashboard.as_view(), name='hostlock_dashboard'),
    path('hostlock_api_guide/', gui.ApiUserGuide.as_view(), name='hostlock_api_guide'),

    # list views
    path('list_locks/', gui.ListLocks.as_view(), name='list_locks'),
    path('list_hosts/', gui.ListHosts.as_view(), name='list_hosts'),
    path('list_my_locks', gui.ListMyLocks.as_view(), name='list_my_locks'),
    path('list_my_hosts', gui.ListMyHosts.as_view(), name='list_my_hosts'),
    path('list_expired_locks', gui.ListExpiredLocks.as_view(), name='list_expired_locks'),

    # action views
    path('release_host_lock', gui.ReleaseHostLock.as_view(), name='release_host_lock'),

    # ajax views
    path('get_lock_auditlog', ajax.get_lock_auditlog, name='get_lock_auditlog'),
    path('get_host_auditlog', ajax.get_host_auditlog, name='get_host_auditlog'),
    path('get_lock_details', ajax.get_lock_details, name='get_lock_details'),


]

padlock/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.auth.views import login, logout_then_login
from userextensions.urls import *
from _common import views as common
from hostlock import views as hostlock

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login, {'template_name': 'registration/login.html'}, name="login"),
    path('logout/', logout_then_login, name="logout"),
    path('detail_user/', common.ShowUserProfile.as_view(), name='detail_user'),

    # app urls
    path('userextensions/', include('userextensions.urls'), ),
    path('hostlock/', include('hostlock.urls'), ),
    path('common/', include('_common.urls'), ),

    # home/default/index urls
    path('', common.PadLockIndex.as_view(), name='index'),
    path(r'default', common.PadLockIndex.as_view(), name='default'),
    path(r'home', common.PadLockIndex.as_view(), name='home'),
    path(r'index', common.PadLockIndex.as_view(), name='index'),

    # swagger API docs
    path('swagger', common.schema_view, name="swagger"),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

urls.py
from django.urls import path
from django.conf.urls import url, include
from rest_framework import routers
from hostlock import apis

app_name = "hostlock"

router = routers.DefaultRouter()

# hostlock API Endpoints
router.register(r'host', apis.HostViewSet, "host")
router.register(r'lock', apis.LockViewSet, "lock")


urlpatterns = [

    # API views
    path('hostlock/', include(router.urls),

]

_common/models.py
"""

"""

_common/views.py
from django.shortcuts import render

from braces.views import LoginRequiredMixin, GroupRequiredMixin

from django.http import HttpResponse
from django.views.generic import (View, TemplateView)
from django.shortcuts import render
from rest_framework import response, schemas
from rest_framework.authtoken.models import Token
from rest_framework.decorators import api_view, renderer_classes
from rest_framework_swagger.renderers import OpenAPIRenderer, SwaggerUIRenderer


# Create your views here.
@api_view()
@renderer_classes([OpenAPIRenderer, SwaggerUIRenderer])
def schema_view(request):
    generator = schemas.SchemaGenerator(title='PadLock APIs')
    return response.Response(generator.get_schema(request=request))


class ShowUserProfile(LoginRequiredMixin, View):
    """ show user profile """
    @staticmethod
    def get(request):
        context = dict()
        context['user'] = request.user
        context['token'] = str(Token.objects.get_or_create(user=request.user)[0])
        context['groups'] = sorted([i.name for i in request.user.groups.all()])
        context['pclouds'] = []
        return render(request, "detail/detail_current_user.html", context)

_common/views/api.py
"""
Description:
    django views for serving RESTful APIs
"""

_common/views/gui.py
"""
Description:
    django views for serving web pages
"""

from django.http import HttpResponse
from django.views.generic import (View, ListView, TemplateView, DeleteView)
from django.shortcuts import render, redirect
from django.contrib import messages
from djangohelpers.views import FilterByQueryParamsMixin
from rest_framework import response, schemas
from rest_framework.authtoken.models import Token
from rest_framework.decorators import api_view, renderer_classes
from rest_framework_swagger.renderers import OpenAPIRenderer, SwaggerUIRenderer
from braces.views import LoginRequiredMixin, GroupRequiredMixin


# import models
from _common.models import (UserPreferences, UserRecent, UserFavorite)



class PadlockBaseListView(FilterByQueryParamsMixin, ListView):
    """ base view for shared PadLock listviews """
    title = None
    table = None
    request = None

    def get(self, request, *args, **kwargs):
        context = dict()
        template = "generic/generic_list.html"
        context['queryset'] = self.filter_by_query_params()
        context['title'] = self.title
        context['sub_title'] = self.page_description
        context['table'] = self.table
        return render(request, template, context=context)


@api_view()
@renderer_classes([OpenAPIRenderer, SwaggerUIRenderer])
def schema_view(request):
    generator = schemas.SchemaGenerator(title='PadLock APIs')
    return response.Response(generator.get_schema(request=request))


class ShowUserProfile(LoginRequiredMixin, View):
    """ show user profile """
    @staticmethod
    def get(request):
        context = dict()
        context['user'] = request.user
        context['token'] = str(Token.objects.get_or_create(user=request.user)[0])
        context['groups'] = sorted([i.name for i in request.user.groups.all()])
        context['pclouds'] = []
        return render(request, "detail/detail_current_user.html", context)


class ShowAdminPage(View):
    """ show the admin page """
    @staticmethod
    def get(request):
        context = dict()
        return render(request, "custom/padlock_admin.html", context)


class UpdateApiToken(LoginRequiredMixin, View):
    """ delete current user token and create a new one """
    def post(self, request):
        redirect_url = self.request.META.get('HTTP_REFERER')
        try:
            token = Token.objects.get(user=request.user)
            token.delete()
            Token.objects.get_or_create(user=request.user)
        except Exception as err:
            messages.add_message(request, messages.ERROR, "Could not complete requested action",
                                 extra_tags='alert-danger')
        return redirect(redirect_url)


class CreateServiceAccount():
    pass


class ListRecents(LoginRequiredMixin, FilterByQueryParamsMixin, ListView):
    """  """
    def get(self, request, *args, **kwargs):
        context = dict()
        self.queryset = UserRecent.objects.filter(user=request.user).order_by('-updated_at')
        template = "generic/generic_list.html"
        context['queryset'] = self.filter_by_query_params()
        context['title'] = "Recents"
        context['sub_title'] = request.user.username
        context['table'] = "table/table_recents.htm"
        return render(request, template, context=context)


class ListFavorites(LoginRequiredMixin, PadlockBaseListView):
    def get(self, request, *args, **kwargs):
        context = dict()
        self.queryset = UserFavorite.objects.filter(user=request.user).order_by('-updated_at')
        template = "generic/generic_list.html"
        context['queryset'] = self.filter_by_query_params()
        context['title'] = "Recents"
        context['sub_title'] = request.user.username
        context['table'] = "table/table_favorites.htm"
        return render(request, template, context=context)


class DeleteRecent():
    pass


class DeleteFavorite():
    pass

_common/views/views_ajax.py
"""
Description:
    django views for serving ajax responses
"""

# import system modules
import json
import datetime

# import django modules
from django.http import HttpResponse
from django.shortcuts import render
from django.template import Context, loader
from django.views.decorators.http import require_GET, require_POST
from django.contrib.auth.models import Group, Permission, User
from django.db.models import Q
from django.utils import timezone

# import models
from hostlock.models import (Host, Lock)


@require_POST
def release_host_lock(request):
    """
    Description:
        release a lock on a host.
    Args:
        request: AJAX request object.
    Returns:
        HttpResponse: JSON formatted response.
    """
    if (request.is_ajax()) and (request.method == 'POST'):
        if 'client_response' in request.POST:
            lock_id = request.POST['client_response']
            lock = Lock.objects.get_object_or_none(id=lock_id)
            lock.release_lock(user=request.user, manual=True)
            return HttpResponse(json.dumps({"msg": 'lock released'}))
        else:
            return HttpResponse("Invalid request inputs", status=400)
    else:
        return HttpResponse("Invalid request", status=400)


def get_host_lock_history(request):
    """ """
    pass

_common/views/views_api.py
"""
Description:
    django views for serving RESTful APIs
"""

_common/views/views_gui.py
"""
Description:
    django views for serving web pages
"""

from django.http import HttpResponse
from django.views.generic import (View, ListView, TemplateView, DeleteView)
from django.shortcuts import render, redirect
from django.contrib import messages
from djangohelpers.views import FilterByQueryParamsMixin
from rest_framework import response, schemas
from rest_framework.authtoken.models import Token
from rest_framework.decorators import api_view, renderer_classes
from rest_framework_swagger.renderers import OpenAPIRenderer, SwaggerUIRenderer
from braces.views import LoginRequiredMixin, GroupRequiredMixin


# import models
from userextensions.models import (UserRecent, UserFavorite)


class PadlockBaseListView(FilterByQueryParamsMixin, ListView):
    """ base view for shared PadLock listviews """
    title = None
    table = None
    request = None

    def get(self, request, *args, **kwargs):
        context = dict()
        template = "generic/generic_list.html"
        context['queryset'] = self.filter_by_query_params()
        context['title'] = self.title
        context['sub_title'] = self.page_description
        context['table'] = self.table
        return render(request, template, context=context)


@api_view()
@renderer_classes([OpenAPIRenderer, SwaggerUIRenderer])
def schema_view(request):
    generator = schemas.SchemaGenerator(title='PadLock APIs')
    return response.Response(generator.get_schema(request=request))


class PadLockIndex(TemplateView):
    """ display PadLock default/home/index page """
    template_name = "padlock_index.html"


class ShowUserProfile(LoginRequiredMixin, View):
    """ show user profile """
    @staticmethod
    def get(request):
        context = dict()
        context['user'] = request.user
        context['token'] = str(Token.objects.get_or_create(user=request.user)[0])
        context['groups'] = sorted([i.name for i in request.user.groups.all()])
        context['pclouds'] = []
        return render(request, "detail/detail_current_user.html", context)


class ShowAdminPage(LoginRequiredMixin, View):
    """ show the admin page """
    @staticmethod
    def get(request):
        context = dict()
        return render(request, "custom/padlock_admin.html", context)


# class UpdateApiToken(LoginRequiredMixin, View):
#     """ delete current user token and create a new one """
#     def post(self, request):
#         redirect_url = self.request.META.get('HTTP_REFERER')
#         try:
#             token = Token.objects.get(user=request.user)
#             token.delete()
#             Token.objects.get_or_create(user=request.user)
#         except Exception as err:
#             messages.add_message(request, messages.ERROR, "Could not complete requested action",
#                                  extra_tags='alert-danger')
#         return redirect(redirect_url)


class CreateServiceAccount():
    pass


class ListRecents(LoginRequiredMixin, FilterByQueryParamsMixin, ListView):
    """  """
    def get(self, request, *args, **kwargs):
        context = dict()
        self.queryset = UserRecent.objects.filter(user=request.user).order_by('-updated_at')
        template = "generic/generic_list.html"
        context['queryset'] = self.filter_by_query_params()
        context['title'] = "Recents"
        context['sub_title'] = request.user.username
        context['table'] = "table/table_recents.htm"
        return render(request, template, context=context)


class ListFavorites(LoginRequiredMixin, PadlockBaseListView):
    def get(self, request, *args, **kwargs):
        context = dict()
        self.queryset = UserFavorite.objects.filter(user=request.user).order_by('-updated_at')
        template = "generic/generic_list.html"
        context['queryset'] = self.filter_by_query_params()
        context['title'] = "Favorites"
        context['sub_title'] = request.user.username
        context['table'] = "table/table_favorites.htm"
        return render(request, template, context=context)

_common/templates/base.htm
{% load staticfiles %}
{% load userextension_tags %}

<!DOCTYPE html>
<!-- project_base.html -->
<html lang="en">
    {% block mainheader %}
    <head>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-144094404-1"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'UA-144094404-1');
        </script>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- get bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        <!-- 3rd party css and js packages -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.3.1/css/hover.css" integrity="sha256-JN6PzDiVqV2siZjedqNB10DTVZsdRKY5oW0TTvYpAuQ=" crossorigin="anonymous" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.1/css/all.css" integrity="sha256-BbA16MRVnPLkcJWY/l5MsqhyOIQr7OpgUAkYkKVvYco=" crossorigin="anonymous" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css" integrity="sha256-HtCCUh9Hkh//8U1OwcbD8epVEUdBvuI8wj1KtqMhNkI=" crossorigin="anonymous" />

        <!-- custom styles & functions -->
        {% get_theme request as user_theme %}
        {% if user_theme %}
            <link href="{% static user_theme.css_file %}" rel="stylesheet">
        {% else %}
            <link href="{% static 'theme_default.css' %}" rel="stylesheet">
        {% endif %}
        <link href="{% static 'padlock_base.css' %}" rel="stylesheet">

        <!-- Local HEAD content -->
        {% block local_head %}{% endblock %}

        <!-- Global Javascript Functions -->
        <script>
            //Django CSRF Functions for AJAX Calls
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie != '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) == (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            var csrftoken = getCookie('csrftoken');
        </script>

        <!-- Local Javascript Functions -->
        {% block local_javascript %}{% endblock %}

    </head>
    {% endblock mainheader %}

    <body style="background-color: gainsboro">

    {% block mainnavbar %}
{#        <nav class="navbar navbar-expand-md navbar-dark bg-primary" style="height: 45px">#}
        <nav class="navbar navbar-expand-md navbar-dark bg-primary">
            <a class="navbar-brand mr-5" href="{% url 'hostlock:home' %}"><b>PadLock</b></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav mr-auto">

                    <!-- hostlock -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            HostLock
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'hostlock:hostlock_dashboard' %}">Dashboard</a></li>
                            <li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="#">Locks</a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'hostlock:list_locks' %}?status=granted&page_description=currently granted">Current Locks</a></li>
                                    <li><a class="dropdown-item" href="{% url 'hostlock:list_expired_locks' %}">Expired Locks</a></li>
                                    <li><a class="dropdown-item" href="{% url 'hostlock:list_locks' %}?status=granted&requester__username={{ user }}&page_description=granted by me">My Locks</a></li>
                                </ul>
                            </li>
                            <li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="#">Hosts</a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'hostlock:list_hosts' %}?is_locked=True&page_description=locked">Locked Hosts</a></li>
                                    <li><a class="dropdown-item" href="{% url 'hostlock:list_my_hosts' %}">My Hosts</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>

                    <!-- apis -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            APIs
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="/hostlock/api/v1/">Developer Tools</a>
                            <a class="dropdown-item" href="/swagger">Documentation <small>(Swagger)</small></a>
                            <a class="dropdown-item" href="{% url 'hostlock:hostlock_api_guide' %}">API Guide</a>
                        </ul>
                    </li>

                    <!-- self-service -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Self-Service
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="#">Request Lock</a>
                            <a class="dropdown-item" href="#">Release Lock</a>
                            <a class="dropdown-item" href="#">Create Service Account</a>
                            <a class="dropdown-item" href="#">Refresh API Token</a>
                        </ul>
                    </li>

                </ul>

                <!-- login -->
                <ul class="navbar-nav mr-4">

                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown align-right">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <b class="fa fa-user fw mr-3"></b><span class="hidden-sm">{{ user }}</span>
                            </a>
                            <div class="dropdown-menu ml-md-n5 ml-lg-n5 ml-sm-0" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'logout' %}"><b class="fa fa-sign-out-alt fw mr-3"></b>Log out</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'detail_user' %}"><i class="fa fa-address-card fw mr-3"></i>Profile</a>
                                <a class="dropdown-item" href="#"><b class="fa fa-cogs fw mr-3 text-greyout"></b>Settings</a>
                                <a class="dropdown-item" href="{% url '_common:list_recents' %}"><b class="far fa-clock fw mr-3"></b>Recents</a>
                                <a class="dropdown-item" href="{% url '_common:list_favorites' %}"><i class="far fa-heart mr-3"></i>Favorites</a>
                                <div class="dropdown-divider"></div>
                                <div class="dropdown-item">
                                    {% is_favorite request as favorite_id %}
                                    {% if favorite_id %}
                                        <form name="submitForm" method="POST" action="{% url 'userextensions:delete_favorite' favorite_id %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="name" value="">
                                            <a href="javascript:document.submitForm.submit()"><i class="fas fa-heart-broken mr-3"></i></b>Remove Favorite</a>
                                        </form>
                                    {% else %}
                                        <form name="submitForm" method="POST" action="{% url 'userextensions:add_favorite' %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="name" value="">
                                            <a href="javascript:document.submitForm.submit()"><b class="fas fa-heart mr-3"></b>Add Favorite</a>
                                        </form>
                                    {% endif %}
                                </div>
                            </div>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}"><b class="fa fa-sign-in fw margin-right-20"></b> Log In </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <br/>

    {% endblock mainnavbar %}

    {% block messages %}
        {% include 'component/show_messages.htm' %}
    {% endblock messages %}

        <div id='page-container' class="container-fluid"> <!-- start "page-container" -->
            <!-- main content loads here-->
            {% block content %} Default Content - Local page should overwrite this {% endblock content %}
        </div>  <!-- end "page-container" -->

    {% block mainfooter %}
        <footer class="footer">
{#            <div class="container-fluid">#}
{#                <span class="">Place sticky footer content here.</span>#}
{#            </div>#}
{#        </footer>#}
    {% endblock mainfooter%}

    </body>
</html>

_common/templates/index2.html
{% extends "base.htm" %}
{% load staticfiles %}

{% block local_head %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css" integrity="sha256-HtCCUh9Hkh//8U1OwcbD8epVEUdBvuI8wj1KtqMhNkI=" crossorigin="anonymous" />
{% endblock %}

{% block content %}
<section class="animated fadeIn">
    <header>
        <div class="headline text-center">
            <br/>
            <div class="container mb-5">
                <h1 class="text-primary"><b>Welcome to PadLock!</b></h1>
                <h5>Select an option below to continue</h5>
            </div>
        </div>
    </header>
</section>

<section class="animated fadeIn">
    <div class="container-fluid">
        <div class="d-flex flex-wrap align-items-center justify-content-center">

            <div class="card mb-4 text-center hvr-grow m-4" style="background-color: whitesmoke; width: 350px; height: 180px;">
                <a href="{% url 'hostlock:hostlock_dashboard' %}">
                    <div class="card-body">
                        <h2 class="card-title text-primary"><i class="fas fa-chart-line"></i></h2>
                        <h3 class="card-title text-primary">Dashboard</h3>
                        <p class="card-text">See the latest lock stats and activity</p>
                    </div>
                </a>
            </div>

            <div class="card mb-4 text-center hvr-grow m-4" style="background-color: whitesmoke; width: 350px; height: 180px;">
                <a href="{% url 'hostlock:list_locks' %}?status=granted&page_description=currently granted">
                    <div class="card-body">
                        <h2 class="card-title text-primary"><i class="fa fa-lock fa-fw"></i></h2>
                        <h3 class="card-title text-primary">Locks</h3>
                        <p class="card-text">View hosts that are currently locked</p>
                    </div>
                </a>
            </div>

            <div class="card mb-4 text-center hvr-grow m-4" style="background-color: whitesmoke; width: 350px; height: 180px;">
                <a href="{% url 'hostlock:list_hosts' %}">
                    <div class="card-body">
                        <h2 class="card-title text-primary"><i class="fa fa-server fa-fw"></i></h2>
                        <h3 class="card-title text-primary">Hosts</h3>
                        <p class="card-text">List host and view lock history</p>
                    </div>
                </a>
            </div>

            <div class="card mb-4 text-center hvr-grow m-4" style="background-color: whitesmoke; width: 350px; height: 180px;">
                <a href="{% url 'hostlock:list_my_locks' %}">
                    <div class="card-body">
                        <h2 class="card-title text-primary"><i class="fa fa-user-lock fa-fw"></i></h2>
                        <h3 class="card-title text-primary">My Locks</h3>
                        <p class="card-text">Manage locks on hosts that you or a team member locked</p>
                    </div>
                </a>
            </div>

            <div class="card mb-4 text-center hvr-grow m-4" style="background-color: whitesmoke; width: 350px; height: 180px;">
                <a href="{% url '_common:show_admin' %}">
                    <div class="card-body">
                        <h2 class="card-title text-primary"><i class="fa fa-id-badge fa-fw"></i></h2>
                        <h3 class="card-title text-primary">Admin</h3>
                        <p class="card-text">Access the administrator features</p>
                    </div>
                </a>
            </div>

            <div class="card mb-4 text-center hvr-grow m-4" style="background-color: whitesmoke; width: 350px; height: 180px;">
                <a href="/admin">
                    <div class="card-body">
                        <h2 class="card-title text-primary"><i class="fab fa-python"></i></h2>
                        <h3 class="card-title text-primary">Django Console</h3>
                        <p class="card-text">Access the django administrator console</p>
                    </div>
                </a>
            </div>

        </div>
    </div>

</section>
{% endblock content %}