hostlock/urls.py
from django.urls import path
from django.conf.urls import include
from rest_framework.routers import DefaultRouter

# import hostlock views and apis
import hostlock.views.views_gui as gui
import hostlock.views.views_api as api
import hostlock.views.views_ajax as ajax

app_name = "hostlock"

router = DefaultRouter()

# hostlock API Endpoints
router.register(r'host', api.HostViewSet, "host")
router.register(r'lock', api.LockViewSet, "lock")
router.register(r'grant_lock', api.GrantLockViewSet, "grant_lock")


urlpatterns = [

    # API views
    path('api/', include(router.urls)),
    path('api/v1/', include(router.urls)),
    path('api/v1/extend_lock/', api.ExtendLockViewSet.as_view()),
    path('api/v1/release_lock/', api.ReleaseLockViewSet.as_view()),
    path('api/v1/check_lock/', api.CheckLockViewSet.as_view()),


    # home page urls
    path('', gui.HostLockIndex.as_view(), name='index'),
    path('home', gui.HostLockIndex.as_view(), name='home'),
    path('default', gui.HostLockIndex.as_view(), name='default'),

    # custom views
    path('hostlock_dashboard/', gui.HostLockDashboard.as_view(), name='hostlock_dashboard'),
    path('hostlock_api_guide/', gui.ApiUserGuide.as_view(), name='hostlock_api_guide'),

    # list views
    path('list_locks/', gui.ListLocks.as_view(), name='list_locks'),
    path('list_hosts/', gui.ListHosts.as_view(), name='list_hosts'),
    path('list_my_locks', gui.ListMyLocks.as_view(), name='list_my_locks'),
    path('list_my_hosts', gui.ListMyHosts.as_view(), name='list_my_hosts'),
    path('list_expired_locks', gui.ListExpiredLocks.as_view(), name='list_expired_locks'),

    # action views
    path('release_host_lock', gui.ReleaseHostLock.as_view(), name='release_host_lock'),

    # ajax views
    path('get_lock_auditlog', ajax.get_lock_auditlog, name='get_lock_auditlog'),
    path('get_host_auditlog', ajax.get_host_auditlog, name='get_host_auditlog'),
    path('get_lock_details', ajax.get_lock_details, name='get_lock_details'),


]

padlock/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.auth.views import login, logout_then_login
from userextensions.urls import *
from _common import views as common
from hostlock import views as hostlock

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login, {'template_name': 'registration/login.html'}, name="login"),
    path('logout/', logout_then_login, name="logout"),
    path('detail_user/', common.ShowUserProfile.as_view(), name='detail_user'),

    # app urls
    path('userextensions/', include('userextensions.urls'), ),
    path('hostlock/', include('hostlock.urls'), ),
    path('common/', include('_common.urls'), ),

    # home/default/index urls
    path('', common.PadLockIndex.as_view(), name='index'),
    path(r'default', common.PadLockIndex.as_view(), name='default'),
    path(r'home', common.PadLockIndex.as_view(), name='home'),
    path(r'index', common.PadLockIndex.as_view(), name='index'),

    # swagger API docs
    path('swagger', common.schema_view, name="swagger"),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

urls.py
from django.urls import path
from django.conf.urls import url, include
from rest_framework import routers
from hostlock import apis

app_name = "hostlock"

router = routers.DefaultRouter()

# hostlock API Endpoints
router.register(r'host', apis.HostViewSet, "host")
router.register(r'lock', apis.LockViewSet, "lock")


urlpatterns = [

    # API views
    path('hostlock/', include(router.urls),

]

hostlock/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views.generic import (View, ListView, DetailView, TemplateView)
from djangohelpers.views import FilterByQueryParamsMixin
from rest_framework.authtoken.models import Token
from itertools import chain
from braces.views import LoginRequiredMixin
from django.contrib import messages
from django.db.models import Q, Count, Sum
import datetime
import collections

# import models
from hostlock.models import (Host, Lock)


# Create your views here.
class HostLockIndex(TemplateView):
    """ super simple view for displaying a page with no queried data """
    template_name = "index2.html"


class HostlockBaseListView(FilterByQueryParamsMixin, ListView):
    """ base view for shared hostlock listviews """
    title = None
    table = None

    def get(self, request, *args, **kwargs):
        context = dict()
        template = "generic/generic_list.html"
        context['queryset'] = self.filter_by_query_params()
        context['title'] = self.title
        context['sub_title'] = self.page_description
        context['table'] = self.table
        return render(request, template, context=context)


class ListLocks(HostlockBaseListView):
    """ list available all hostlock lock entries  """
    queryset = Lock.objects.all().select_related('host', 'host__owner', 'requester').order_by('-created_at')
    title = "Locks"
    page_description = ""
    table = "table/table_locks.htm"


class ListHosts(HostlockBaseListView):
    """ list available all hostlock host entries  """
    queryset = Host.objects.all().select_related('owner').prefetch_related('lock_set')
    title = "Hosts"
    page_description = "with lock activity"
    table = "table/table_hosts.htm"


class ListMyLocks(LoginRequiredMixin, View):
    """ list current locks that have been granted to user, or a group user is a member of """
    @staticmethod
    def get(request):
        template = 'custom/show_my_locks.html'
        context = dict()
        context['title'] = "Locks for"
        context['sub_title'] = request.user.username
        context['table'] = "table/table_locks.htm"
        context['user_locks'] = Lock.objects.filter(requester=request.user, status='granted')\
            .select_related('requester', 'host', 'host__owner')
        group_locks = Lock.objects.none()
        for group_name in request.user.groups.all():
            group_locks = group_locks | Lock.objects.filter(requester__groups__name=group_name, status='granted')\
                .select_related('requester', 'host', 'host__owner')
        context['group_locks'] = group_locks.exclude(requester=request.user)
        context['historical_locks'] = Lock.objects.filter(requester=request.user).exclude(status='granted')\
            .select_related('requester', 'host', 'host__owner')
        context['stale_locks'] = group_locks.exclude()

        return render(request, template, context=context)


class ReleaseHostLock(View):
    """ manually release lock on a given host """
    def post(self, request, *args, **kwargs):
        """ process POST request """
        redirect_url = self.request.META.get('HTTP_REFERER')
        lock_id = self.request.GET.dict().get('id', None)
        lock = Lock.objects.get_object_or_none(id=lock_id)
        if lock:
            if lock.release_lock(user=request.user, manual=True):
                messages.add_message(request, messages.ERROR, "failed to release lock",
                                     extra_tags='alert-danger', )
            else:
                messages.add_message(request, messages.ERROR, "Lock released!",
                                     extra_tags='alert-success', )
        return redirect(redirect_url)


class ExtendLock(View):
    """ increase the expire date for a given lock """
    def post(self, request, *args, **kwargs):
        """ process POST request """
        redirect_url = self.request.META.get('HTTP_REFERER')
        lock_id = self.request.GET.dict().get('id', None)
        minutes = self.request.GET.dict().get('minutes', None)
        if not minutes:
            messages.add_message(request, messages.ERROR, "can not extend lock by 0 minutes",
                                 extra_tags='alert-warning', )
            return redirect(redirect_url)
        lock = Lock.objects.get_object_or_none(id=lock_id)
        if lock:
            if lock.extend_lock(user=request.user, minutes=minutes):
                messages.add_message(request, messages.ERROR, "failed to extend lock",
                                     extra_tags='alert-danger', )
            else:
                messages.add_message(request, messages.ERROR, "Lock extended by {}".format(minutes),
                                     extra_tags='alert-success', )
        return redirect(redirect_url)


class SelfServicePanel(View):
    """ 'control panel' like self-service page to perform actions such as:
        - update a token
        - create a service account
        - list assets by ownership
        - disable locking for a host or service
        - view action history
        - view/manage locks or owned assets
    """
    pass


class AdminPanel(View):
    """ 'control panel' like view for admins to perform actions such as:
    - revoke a user token
    - disable locking for a host or service
    - list/release/manager current locks
    - delete a host or service
    - view/manage stale locks
    """
    pass


# class ApiUserGuide(TemplateView):
#     """ show information/examples on using each available API """
#     template_name = "help/api_guide.html"


class ApiUserGuide(LoginRequiredMixin, View):
    """ show information/examples on using each available API """
    @staticmethod
    def get(request):
        print("TEST: ", request.META)
        # template = "help/api_guide.html"
        template = "custom/show_api_guide.html"
        context = dict()
        context['title'] = 'API Guide'
        context['sub_title'] = "HostLock"
        context['token'] = str(Token.objects.get_or_create(user=request.user)[0])
        return render(request, template, context=context)


class HostLockDashboard(LoginRequiredMixin, View):
    """ show a consolidated view containing summarized information regarding host locks """
    # @staticmethod
    def get_24hr_trend_data(self, queryset, timestamp="created_at"):
        """ """
        print("TEST: getting 24hr data...")
        last_day_data = queryset.filter(created_at__gte=(timezone.now() - datetime.timedelta(days=1)))
        print("TEST: ", last_day_data)
        data = {}
        now = timezone.now()
        # for hour in range(0, 24):
        for hour in [(now - datetime.timedelta(hours=i)).hour for i in range(0, 24)]:
            date_diff = now - datetime.timedelta(hours=hour)
            if timestamp == "updated_at":
                data[date_diff.hour] = last_day_data.filter(updated_at__hour=hour).count()
            else:
                data[date_diff.hour] = last_day_data.filter(created_at__hour=hour).count()
        print(data)
        return data

    # @staticmethod
    def get(self, request):
        template = 'custom/show_hostlock_dashboard.html'
        context = dict()
        now = timezone.now()
        all_locks = Lock.objects.filter().select_related('requester', 'host', 'host__owner')
        all_granted_locks = all_locks.filter(status='granted').select_related('requester', 'host', 'host__owner')
        all_released_locks = all_locks.filter(status__in=['released', 'manually released'])
        all_expired_locks = all_granted_locks.filter(no_expire=False, expires_at__lt=now)
        group_locks = Lock.objects.none()
        if request.user and request.user != 'AnonymousUser':
            for group_name in request.user.groups.all():
                group_locks = group_locks | all_granted_locks.filter(requester__groups__name=group_name)
            context['manageable_locks'] = group_locks.distinct() | all_granted_locks.filter(requester=request.user).distinct()
        trend_data = {
            'granted': self.get_24hr_trend_data(all_locks),
            'released': self.get_24hr_trend_data(all_released_locks, timestamp="updated_at"),
            'expired': self.get_24hr_trend_data(all_expired_locks, timestamp="updated_at"),
        }
        context['granted_locks'] = all_granted_locks
        context['current_locks'] = all_granted_locks.filter(Q(expires_at__gte=now) | Q(expires_at=None)).order_by('-created_at')
        context['expired_locks'] = all_granted_locks.filter(expires_at__lt=now).order_by('-created_at')
        context['trend_data'] = trend_data
        return render(request, template, context=context)

hostlock/views/views_ajax.py
"""
Views used specifically for handling AJAX Requests
"""
# import system modules
import json

# import django modules
from django.http import HttpResponse
from django.template import Context, loader
from django.views.decorators.http import require_GET, require_POST

# import models
from auditlog.models import LogEntry
from hostlock.models import Lock

# import serializers
from hostlock.serializers import (HostSerializer, LockSerializer)


@require_GET
def get_host_auditlog(request):
    """
    Description:
        get AuditLog for a given Host.
    Args:
        request: AJAX request object.
    Returns:
        HttpResponse: JSON formatted response.
    """
    if (request.is_ajax()) and (request.method == 'GET'):
        if 'client_response' in request.GET:
            hostname = request.GET['client_response']
            queryset = LogEntry.objects.filter(content_type__model="host",
                                               object_repr__icontains=hostname)
            template = loader.get_template('ajax/show_audit_log.htm')
            return HttpResponse(json.dumps({"server_response": template.render({'queryset': queryset})}),
                                content_type='application/javascript')
        else:
            return HttpResponse("Invalid request inputs", status=400)
    else:
        return HttpResponse("Invalid request", status=400)


@require_GET
def get_lock_auditlog(request):
    """
    Description:
        get AuditLog for a given Lock.
    Args:
        request: AJAX request object.
    Returns:
        HttpResponse: JSON formatted response.
    """
    if (request.is_ajax()) and (request.method == 'GET'):
        if 'client_response' in request.GET:
            lock = request.GET['client_response']
            queryset = LogEntry.objects.filter(content_type__model="lock",
                                               object_repr__icontains=lock)
            template = loader.get_template('ajax/show_audit_log.htm')
            return HttpResponse(json.dumps({"server_response": template.render({'queryset': queryset})}),
                                content_type='application/javascript')
        else:
            return HttpResponse("Invalid request inputs", status=400)
    else:
        return HttpResponse("Invalid request", status=400)


@require_POST
def release_host_lock(request):
    """
    Manually release a lock on a host
    :param request:
        ajax request object
    :return:
        JSON formatted response
    """
    if (request.is_ajax()) and (request.method == 'POST'):
        if 'client_response' in request.POST:
            lock = request.GET['client_response']
    lock_id = request.POST['client_response']
    lock = Lock.objects.get(id=lock_id)
    if lock.release_lock(user=request.user, manual=True):
        return HttpResponse(json.dumps({'msg': 'Failed to release lock on {}'.format(lock.host.hostname)}), status=400)
    else:
        return HttpResponse(json.dumps({'msg': 'Lock on {} successfully released'.format(lock.host.hostname)}))


# @require_GET
# def get_lock_details(request):
#     """
#     Description:
#         Get all fields for a given lock id.
#     Args:
#         request: AJAX request object.
#     Returns:
#         HttpResponse: JSON formatted response.
#     """
#     if (request.is_ajax()) and (request.method == 'GET'):
#         if 'client_response' in request.GET:
#             obj_id = request.GET['client_response']
#             obj = Lock.objects.get(id=obj_id)
#             serialized_obj = LockSerializer(obj)
#             template = loader.get_template('ajax/show_object_details.htm')
#             # return HttpResponse(json.dumps({"server_response": template.render({'object': obj})}),
#             #                     content_type='application/javascript')
#             return HttpResponse(json.dumps({"server_response": template.render({'object': serialized_obj.data})}),
#                                 content_type='application/javascript')
#         else:
#             return HttpResponse("Invalid request inputs", status=400)
#     else:
#         return HttpResponse("Invalid request", status=400)

@require_GET
def get_lock_details(request):
    """
    Description:
        Get all fields for a given lock id.
    Args:
        request: AJAX request object.
    Returns:
        HttpResponse: JSON formatted response.
    """
    if (request.is_ajax()) and (request.method == 'GET'):
        if 'client_response' in request.GET:
            obj_id = request.GET['client_response']
            obj = Lock.objects.get(id=obj_id)
            template = loader.get_template('ajax/detail_hostlock.htm')
            return HttpResponse(json.dumps({"server_response": template.render({'object': obj})}),
                                content_type='application/javascript')
        else:
            return HttpResponse("Invalid request inputs", status=400)
    else:
        return HttpResponse("Invalid request", status=400)

hostlock/templates/table/table_hosts.htm
<table class="table table-condensed table-bordered table-striped" data-toggle="table" data-search="true"
       data-flat="true" data-pagination="true" data-show-pagination-switch="true" data-show-columns="true"
       data-show-export="true" data-reorderable-columns="true" data-resizable="false" data-export-types="['excel','csv','txt','sql']">
    <thead>
    <tr>
        <th data-field="hostname" data-sortable="true">Hostname</th>
        <th data-field="owner" data-sortable="true">Owner</th>
        <th data-field="is_locked" data-sortable="true">Is Locked?</th>
        <th data-field="historical" data-sortable="true">Prior Locks</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for row in queryset %}
        <tr>
            <td>{{ row.hostname }}</td>
            <td>{{ row.owner }}</td>
            <td>
                {% if row.is_locked %}
                <span class="text-primary"><i class="fa fa-check fa-fw"></i></span>
                {% else %}
                <span class="text-danger"><i class="fa fa-times fa-fw"></i></span>
                {% endif %}
            </td>
            <td>{{ row.lock_set.count }}</td>

            <!-- actions -->
            <td>

                <!-- lock history -->
                <a href="#" class="" title="view audit log"
                   onClick="showInfo('{% url "hostlock:get_host_auditlog" %}', '{{ row.hostname }}', 'Audit Log: <small><i>{{ row.hostname }}</i></small>', 'xl');"
                   role="button" data-toggle="tooltip" data-placement="left">
                    <i class="fa fa-history fa-fw"></i>
                </a>

                <!-- view lock details -->
                {% if row.is_locked %}
                    {% for lock in row.lock_set.all %}
                        {% if lock.status == 'granted' %}
                    <a href="#" class="table-action-icon" title="view lock details"
                       onClick="showInfo('{% url "hostlock:get_lock_details" %}', '{{ lock.id }}', 'Lock Details: <small><i>{{ row.hostname }}</i></small>', true);"
                       role="button" data-toggle="tooltip" data-placement="left">
                        <i class="fa fa-info-circle fa-fw"></i>
                    </a>
                        {% endif %}
                    {% endfor %}
                {% endif %}

            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

hostlock/templates/table/table_locks.htm
<table class="table table-condensed table-bordered table-striped" data-toggle="table" data-search="true"
       data-flat="true" data-pagination="true" data-show-pagination-switch="true" data-show-columns="true"
       data-show-export="true" data-reorderable-columns="true" data-resizable="false" data-export-types="['excel','csv','txt','sql']">
    <thead>
    <tr>
        <th data-field="host" data-sortable="true">Host</th>
        <th data-field="status" data-sortable="true">Status</th>
        <th data-field="requester" data-sortable="true">Requester</th>
        <th data-field="owner" data-sortable="true">Owner</th>
        <th data-field="created_at" data-sortable="true">Created At</th>
        <th data-field="expiration" data-sortable="true">Expires At</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for row in queryset %}
        <tr>
            <td>{{ row.host }}</td>
            <td>{{ row.status }}</td>
            <td>{{ row.requester }}</td>
            <td>{{ row.host.owner }}</td>
            <td>{{ row.created_at|date:'Y-m-d H:i:s' }}</td>
            <td>{{ row.expires_at|date:'Y-m-d H:i:s' }}</td>
            <!-- actions -->
            <td>

{#                <!-- extend lock -->#}
{#                <a href="#" class="table-action-icon" title="extend lock time"#}
{#                   onClick="confirmAction('{% url 'hostlock:release_host_lock' %}?id={{ row.id }}', 'Unlock Host', 'This will release the current lock on <b><i>{{ row.host }}</i></b>. Do you wish to continue?', 'Continue', 'POST');"#}
{#                   role="button" data-toggle="tooltip" data-placement="left">#}
{#                    <i class="fa fa-lock"></i>#}
{#                </a>#}

                <!-- view lock details -->
                <a href="#" class="table-action-icon" title="view lock details"
                   onClick="showInfo('{% url "hostlock:get_lock_details" %}', '{{ row.id }}', 'Lock Details: <small><i>{{ row.id }}</i></small>', true);"
                   role="button" data-toggle="tooltip" data-placement="left">
                    <i class="fa fa-info-circle fa-fw"></i>
                </a>

                <!-- view lock history -->
                <a href="#" class="table-action-icon" title="view audit log"
                   onClick="showInfo('{% url "hostlock:get_lock_auditlog" %}', '{{ row.id }}', 'Audit Log: <small><i>{{ row.host }}</i></small>', 'xl');"
                   role="button" data-toggle="tooltip" data-placement="left">
                    <i class="fa fa-history fa-fw"></i>
                </a>

                <!-- manually unlock host -->
                {% if row.status == 'granted' or row.status == 'expired' %}
                    <a href="#" class="table-action-icon" title="unlock host"
                       onClick="confirmAction('{% url 'hostlock:release_host_lock' %}?id={{ row.id }}', 'Unlock Host', 'This will release the current lock on <b><i>{{ row.host }}</i></b>. Do you wish to continue?', 'Continue', 'POST');"
                       role="button" data-toggle="tooltip" data-placement="left">
                        <i class="fa fa-lock-open"></i>
                    </a>
                {% endif %}

            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>